language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install ."
  - "pip install -r requirements-dev.txt"

# command to run tests, e.g. python setup.py test
script:  py.test

services:
  - redis-server

matrix:
  allow_failures:
    - python: "3.7"
